feat: add tag existence verification in release workflow

diff --git a/.github/workflows/reusable_release_notes.yaml b/.github/workflows/reusable_release_notes.yaml
--- a/.github/workflows/reusable_release_notes.yaml
+++ b/.github/workflows/reusable_release_notes.yaml
@@ -60,6 +60,22 @@ jobs:
 
       - name: Fetch all tags
         run: git fetch --tags
+        
+      - name: Verify existence of from-tag (${{ inputs.from-tag || 'Empty' }})
+        if: ${{ inputs.from-tag != '' }}
+        run: |
+          if ! git tag --list | grep -q "^${{ inputs.from-tag }}$"; then
+            echo "Error: Specified from-tag '${{ inputs.from-tag }}' does not exist in the repository." >&2
+            exit 1
+          fi
+
+      - name: Verify existence of to-tag (${{ inputs.to-tag || 'Empty' }})
+        if: ${{ inputs.to-tag != '' }}
+        run: |
+          if ! git tag --list | grep -q "^${{ inputs.to-tag }}$"; then
+            echo "Error: Specified to-tag '${{ inputs.to-tag }}' does not exist in the repository." >&2
+            exit 1
+          fi
 
       - name: Override from-tag
         if: ${{ inputs.derive-from-tag == true && inputs.from-tag == '' }}
