refactor: update workflows for modular structure and clarity

diff --git a/.github/workflows/test-merge-and-push.yaml b/.github/workflows/test-merge-and-push.yaml
--- a/.github/workflows/test-merge-and-push.yaml
+++ b/.github/workflows/test-merge-and-push.yaml
@@ -4,9 +4,11 @@ on:
   workflow_dispatch:
 
 jobs:
-  create-and-test-branches:
-    runs-on: ubuntu-latest
-
+  create-branches:
+    runs-on: ubuntu-22.04
+    env:
+      target-branch: ${{ steps.create-branches.outputs.target-branch }}
+      push-branch: ${{ steps.create-branches.outputs.push-branch }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -52,46 +54,55 @@ jobs:
             git commit -m "Add push branch file"
             git push origin $push_branch
           fi
+    
+  merge-and-push:
+    needs: [create-branches]
+    uses: ./.github/workflows/reusable-merge-and-push.yaml
+    secrets:
+      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
+      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
+    with:
+      target-branch: ${{ needs.create-branches.outputs.target-branch }}
+      push-branch: ${{ needs.create-branches.outputs.push-branch }}
 
-      - name: Trigger Reusable Merge and Push
-        uses: ./.github/workflows/reusable-merge-and-push.yaml
-        secrets:
-          BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
-          BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
-        with:
-          target-branch: ${{ steps.generate-branches.outputs.target-branch }}
-          push-branch: ${{ steps.generate-branches.outputs.push-branch }}
+  verify-merge:
+    needs: [create-branches, merge-and-push]
+    runs-on: ubuntu-22.04
+    steps:
+    - name: Verify Merge (${{ needs.create-branches.outputs.target-branch }} -> ${{ needs.create-branches.outputs.push-branch }})
+      id: verify-merge-target-branch
+      run: |
+        set -e
+        target_branch=${{ needs.create-branches.outputs.target-branch }}
+        push_branch=${{ needs.create-branches.outputs.push-branch }}
 
-      - name: Verify Merge (${{ steps.generate-branches.outputs.target-branch }} -> ${{ steps.generate-branches.outputs.push-branch }})
-        id: verify-merge-target-branch
-        run: |
-          set -e
-          target_branch=${{ steps.generate-branches.outputs.target-branch }}
-          push_branch=${{ steps.generate-branches.outputs.push-branch }}
+        git fetch origin $push_branch
 
-          git fetch origin $push_branch
+        if git merge-base --is-ancestor origin/$target_branch origin/$push_branch; then
+          echo "$target_branch is already merged into $push_branch."
+          echo "can-delete=true" >> $GITHUB_OUTPUT
+        else
+          echo "::error::$target_branch is not merged into $push_branch. Aborting deletion."
+          echo "can-delete=false" >> $GITHUB_OUTPUT
+          exit 1
+        fi
 
-          if git merge-base --is-ancestor origin/$target_branch origin/$push_branch; then
-            echo "$target_branch is already merged into $push_branch."
-            echo "can-delete=true" >> $GITHUB_OUTPUT
-          else
-            echo "::error::$target_branch is not merged into $push_branch. Aborting deletion."
-            echo "can-delete=false" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-
-      - name: Delete Target Branch (${{ steps.generate-branches.outputs.target-branch }})
+  delete-branch:
+    needs: [create-branches, merge-and-push, verify-merge]
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Delete Target Branch (${{ needs.create-branches.outputs.target-branch }})
         uses: ./.github/workflows/reusable-clean-packagejson-branch.yaml
         secrets:
           BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
           BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
         with:
-          branch: ${{ steps.generate-branches.outputs.target-branch }}
+          branch: ${{ needs.create-branches.outputs.target-branch }}
 
-      - name: Delete Push Branch (${{ steps.generate-branches.outputs.push-branch }})
+      - name: Delete Push Branch (${{ needs.create-branches.outputs.push-branch }})
         uses: ./.github/workflows/reusable-clean-packagejson-branch.yaml
         secrets:
           BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
           BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
         with:
-          branch: ${{ steps.generate-branches.outputs.push-branch }}
+          branch: ${{ needs.create-branches.outputs.push-branch }}
