feat: simplify token management in workflows

diff --git a/.github/workflows/update-packagejson.yaml b/.github/workflows/update-packagejson.yaml
--- a/.github/workflows/update-packagejson.yaml
+++ b/.github/workflows/update-packagejson.yaml
@@ -4,34 +4,36 @@ on:
   workflow_call:
     inputs:
       file-path:
-        description: "Paths of files to update"
+        description: "package.json path to update. You can input multiline paths. Supported files are `package.json`, `plugin.cfg` and `Directory.Build.props`"
         required: true
         type: string
       tag:
-        description: "Version tag to use in updates"
+        description: "git tag you want create. (sample 1.0.0)"
         required: true
         type: string
       dry-run:
-        description: "Simulate changes without pushing"
+        description: "true to simularate commit but not push change."
         required: true
         type: boolean
       ref:
-        description: "Git reference to checkout"
+        description: "checkout ref"
         required: false
         type: string
         default: ''
     secrets:
-      CUSTOM_GITHUB_TOKEN:
+      BOT_APP_ID:
+        required: true
+      BOT_PRIVATE_KEY:
         required: true
     outputs:
       sha:
-        description: "Git commit's SHA"
+        description: "Git commit sha after package.json has changed."
         value: ${{ jobs.update-packagejson.outputs.sha }}
       branch-name:
-        description: "Branch created name"
+        description: Git branch name created.
         value: ${{ jobs.update-packagejson.outputs.branch-name }}
       is-branch-created:
-        description: "Whether a branch was created"
+        description: Indicate is Git branch created or not.
         value: ${{ jobs.update-packagejson.outputs.is-branch-created }}
 
 jobs:
@@ -50,13 +52,23 @@ jobs:
       branch-name: ${{ steps.configure.outputs.branch-name }}
       is-branch-created: ${{ steps.commit.outputs.is-branch-created }}
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+      - name: Generate Token
+        id: app-token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ secrets.BOT_APP_ID }}
+          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
+
+      - name: Configure Output variables
+        id: configure
+        run: |
+          echo "branch-name=test-release/${{ inputs.tag }}" | tee -a "$GITHUB_OUTPUT"
+
+      - uses: actions/checkout@v4
         with:
           ref: ${{ inputs.ref }}
           fetch-depth: 0
-          # ここを`true`にすることで既存トークンを利用可能にします
-          persist-credentials: true
+          persist-credentials: false
 
       - name: Update files to version ${{ needs.validate.outputs.normalized_tag }}
         run: |
@@ -73,7 +85,9 @@ jobs:
 
             echo "::group::Updating"
               if [[ "${file_name}" == "package.json" ]]; then
+                # Unity `"version": "VersionString",`
                 sed -i -e "s/\(\"version\":\) \"\(.*\)\",/\1 \"${{ needs.validate.outputs.normalized_tag }}\",/" "${file_path}"
+                actual=$(grep "version" "$file_path" | cut -d ':' -f 2 | tr -d ',' | tr -d '"' | tr -d ' ')
               else
                 echo "Unknown file name ${file_name} is specified."
                 exit 1
@@ -83,28 +97,43 @@ jobs:
             echo "::group::After"
               cat "$file_path"
             echo "::endgroup::"
+
+            echo "::group::Validate Change"
+              if [[ "$actual" != "$expected" ]]; then
+                echo "Failed. Path: $file_path, Expected: $expected, Actual: $actual"
+                exit 1
+              else
+                echo "Success. Path: $file_path, Expected: $expected, Actual: $actual"
+              fi
+            echo "::endgroup::"
           done <<< "${{ inputs.file-path }}"
 
-      - name: Commit changes
+      - name: Check update on git
+        id: check_update
+        run: git diff --exit-code || echo "changed=1" | tee -a "$GITHUB_OUTPUT"
+
+      - name: Commit files (updated? = ${{ steps.check_update.outputs.changed == '1' }})
         id: commit
-        env:
-          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
         run: |
-          if [[ "${{ inputs.dry-run }}" != "true" ]]; then
+          if [[ "${{ steps.check_update.outputs.changed }}" == "1" ]]; then
             git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git config --local user.name "github-actions[bot]"
-            git commit -am "feat: Update package.json to ${{ inputs.tag }}"
+            git commit -m "feat: Update package.json to ${{ needs.validate.outputs.normalized_tag }}" -m "Commit by [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" -a
             echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"
-            echo "branch-name=test-release/${{ inputs.tag }}" | tee -a "$GITHUB_OUTPUT"
-            echo "is-branch-created=true" | tee -a "$GITHUB_OUTPUT"
+            echo "is-branch-created=${{ inputs.dry-run }}" | tee -a "$GITHUB_OUTPUT"
+          elif [[ "${{ inputs.ref }}" != "" ]]; then
+            echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"
+            echo "is-branch-created=false" | tee -a "$GITHUB_OUTPUT"
           else
-            echo "Dry-run only, no changes committed."
+            echo "sha=" | tee -a "$GITHUB_OUTPUT"
             echo "is-branch-created=false" | tee -a "$GITHUB_OUTPUT"
           fi
 
       - name: Push changes
-        if: ${{ steps.commit.outputs.is-branch-created == 'true' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
-        run: |
-          git push origin HEAD:${{ inputs.ref }}
+        if: ${{ steps.check_update.outputs.changed == '1' }}
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ steps.app-token.outputs.token }}
+          branch: ${{ inputs.ref }}
+          tags: false
+          force: ${{ inputs.dry-run }}
